git:
  submodules: true
language: scala

cache:
  directories:
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin
    CHISEL3=3.3-SNAPSHOT
    CHISEL_TESTERS=1.4-SNAPSHOT

install:
  - bash .install_verilator.sh

script:
  - set -o pipefail && sbt -Dchisel3Version=$CHISEL3 -Dchisel-iotestersVersion=$CHISEL_TESTERS test
